-- ============================================================================
-- T1 — Tool "Lá Số Người Khác": nhập lá số sếp/đồng nghiệp/người thân → cẩm
-- nang ứng xử với đúng người đó.
-- ----------------------------------------------------------------------------
-- Không thêm cổ pháp nào: engine đọc lại các cung đã có qua một lăng kính khác
-- (`lib/engine/nguoi-khac.ts`). Migration này chỉ dựng chỗ chứa lịch sử + đăng
-- ký giá.
--
-- Bảng RIÊNG, không nhét vào `user_charts` (sổ lá số của U4): sổ trả lời "tôi
-- đã lưu lá số của ai", bảng này trả lời "tôi đã trả tiền cho bản luận nào".
-- Trộn chung thì mỗi lần lưu một lá số vào sổ sẽ trông như đã mua một bản luận.
--
-- ⚠️ `tool_pricing` CỐ Ý `enabled=false` — `cong-cu.html` và `tuvi-paywall.js`
-- đều lọc `enabled=eq.true`, bật TRƯỚC khi deploy là tool hiện trên trang Công
-- Cụ trong khi trang chưa tồn tại ⇒ 404 cho người thật. Câu bật nằm ở cuối file.
-- ============================================================================

create table if not exists public.nguoi_khac_reports (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null references auth.users(id) on delete cascade,
  created_at  timestamptz not null default now(),
  -- Nhãn người xem tự đặt ("Sếp Hùng"). Không phải danh tính, chỉ để nhận ra
  -- trong danh sách lịch sử.
  ten         text,
  quan_he     text,
  quan_he_label text,
  kieu        text,
  kieu_ten    text,
  -- Khoá canonical (lá số người được xem + quan hệ) — cũng là chỗ tra "user
  -- này đã trả cho bản luận nào" để cho xem lại miễn phí.
  laso_key    text
);

create index if not exists nguoi_khac_reports_user_idx on public.nguoi_khac_reports (user_id, created_at desc);
create index if not exists nguoi_khac_reports_laso_idx on public.nguoi_khac_reports (laso_key);

alter table public.nguoi_khac_reports enable row level security;

-- Chủ sở hữu đọc bản của mình; ghi chỉ qua service key (route server).
--
-- ⚠️ CỐ Ý KHÔNG có policy cho admin. Khác các bảng chân dung: ở đây mỗi dòng
-- là bằng chứng "người dùng X đang dò tính cách của người Y". Bảng chân dung
-- lưu kết quả người ta CHỦ ĐỘNG đem đi khoe; bảng này thì ngược lại. Cần số
-- liệu vận hành thì đếm qua `credit_transactions`, không cần đọc nội dung.
drop policy if exists nguoi_khac_reports_owner_read on public.nguoi_khac_reports;
create policy nguoi_khac_reports_owner_read on public.nguoi_khac_reports
  for select using (auth.uid() = user_id);

-- ─── Đăng ký giá ────────────────────────────────────────────────────────────
-- 15 Lượng: rẻ hơn Luận Giải Lá Số (25) vì bản này ngắn hơn và chỉ đọc 5 mặt.
-- Cố ý để rẻ — mỗi lượt là thêm một lá số nhập vào hệ thống, đó mới là thứ
-- đáng giá hơn phần chênh 10 Lượng.
insert into public.tool_pricing (tool_id, label, credits, icon, category, sort_order, is_free, description, enabled, need_tags, question)
values (
  'nguoi-khac',
  'Lá Số Người Khác',
  15,
  '👤',
  'Luận Giải',
  63,
  false,
  'Nhập lá số sếp, đồng nghiệp, cấp dưới hay người thân — nhận bản cẩm nang ứng xử: họ vận hành thế nào, nên nói gì, tránh nói gì, và lúc nào nên đưa việc lớn tới.',
  false,
  'cong-viec,hieu-minh',
  'Làm sao nói chuyện được với sếp/đồng nghiệp này?'
)
on conflict (tool_id) do update set
  label       = excluded.label,
  credits     = excluded.credits,
  icon        = excluded.icon,
  category    = excluded.category,
  sort_order  = excluded.sort_order,
  is_free     = excluded.is_free,
  description = excluded.description,
  need_tags   = excluded.need_tags,
  question    = excluded.question,
  updated_at  = now();

-- ─── VIỆC TAY: chạy SAU khi deploy xong ─────────────────────────────────────
-- update public.tool_pricing set enabled = true, updated_at = now()
--  where tool_id = 'nguoi-khac';
