-- ============================================================================
-- T6 — Tool "Duyên Nợ Tiền Kiếp": HAI lá số → một mối duyên ở kiếp trước.
-- ----------------------------------------------------------------------------
-- Engine `lib/engine/past-life-bond.ts` đã có sẵn và đã verify 950 cặp, chỉ
-- thiếu tầng sản phẩm. Migration này dựng chỗ chứa lịch sử + đăng ký giá.
--
-- Bảng RIÊNG chứ không nhét vào `past_life_portraits`: bảng kia trả lời "lá số
-- này ra nhân vật gì" (một người, một chức phận, một tuổi vẽ), bảng này trả lời
-- "cặp lá số này ra mối duyên gì" (hai nhân vật, một loại duyên). Nhồi chung
-- thì quá nửa số cột luôn NULL ở một trong hai bên, và `action=history` của cả
-- hai tool phải học cách bỏ qua dòng của tool kia.
--
-- ⚠️ `tool_pricing` CỐ Ý `enabled=false`: `cong-cu.html` và `tuvi-paywall.js`
-- đều lọc `enabled=eq.true`, bật TRƯỚC khi deploy là công cụ hiện trên trang
-- Công Cụ trong khi trang chưa tồn tại ⇒ 404 cho người thật. Bật sau khi deploy
-- bằng câu SQL ghi ở cuối file.
-- ============================================================================

create table if not exists public.past_life_bonds (
  id            bigint generated by default as identity primary key,
  user_id       uuid not null references auth.users(id) on delete cascade,
  created_at    timestamptz not null default now(),
  -- Loại duyên (khoá cổ pháp) + nhãn tiếng Việt. Lưu CẢ HAI: khoá để truy vấn
  -- và thống kê, nhãn để hiện lại lịch sử mà không phải đồng bộ bảng tra trong
  -- code — đổi chữ trong engine thì bản đã lưu vẫn đọc đúng như lúc người ta xem.
  bond_kind     text,
  bond_label    text,
  character_a   text,
  character_b   text,
  occupation_a  text,
  occupation_b  text,
  era           text,
  image_url     text not null,
  -- Khoá canonical của CẶP lá số (đã sắp thứ tự) — xem normalizePair trong
  -- app/api/duyen-no-tien-kiep/route.ts. Đây cũng là chỗ tra "user này đã trả
  -- cho cặp lá số nào" để cho xem lại miễn phí.
  laso_key      text
);

create index if not exists past_life_bonds_user_idx on public.past_life_bonds (user_id, created_at desc);
create index if not exists past_life_bonds_laso_idx on public.past_life_bonds (laso_key);

alter table public.past_life_bonds enable row level security;

-- Cùng khuôn RLS với `past_life_portraits`: chủ sở hữu đọc bản của mình; ghi
-- chỉ qua service key (route server), không mở cho anon/authenticated.
drop policy if exists past_life_bonds_owner_read on public.past_life_bonds;
create policy past_life_bonds_owner_read on public.past_life_bonds
  for select using (auth.uid() = user_id);

drop policy if exists past_life_bonds_admin_read on public.past_life_bonds;
create policy past_life_bonds_admin_read on public.past_life_bonds
  for select using (auth.jwt() ->> 'email' = 'admin@tuviminhbao.com');

-- ─── Đăng ký giá ────────────────────────────────────────────────────────────
-- 30 Lượng: đắt hơn Chân Dung Tiền Kiếp (25) vì phải dựng HAI nhân vật trong
-- một khung và lập hai lá số, nhưng chia đôi cho hai người thì mỗi bên vẫn rẻ
-- hơn tự vẽ riêng — đó là điểm khiến người ta rủ nhau chạy chung.
insert into public.tool_pricing (tool_id, label, credits, icon, category, sort_order, is_free, description, enabled, need_tags, question)
values (
  'duyen-no-tien-kiep',
  'Duyên Nợ Tiền Kiếp',
  30,
  '🏯',
  'Luận Giải',
  62,
  false,
  'Hai lá số → một mối duyên ở kiếp trước: loại duyên nợ suy từ cổ pháp, câu chuyện 4 hồi và một bức tranh vẽ cả hai người.',
  false,
  'tinh-duyen',
  'Kiếp trước tôi với người ấy là gì của nhau?'
)
on conflict (tool_id) do update set
  label       = excluded.label,
  credits     = excluded.credits,
  icon        = excluded.icon,
  category    = excluded.category,
  sort_order  = excluded.sort_order,
  is_free     = excluded.is_free,
  description = excluded.description,
  need_tags   = excluded.need_tags,
  question    = excluded.question,
  updated_at  = now();

-- ─── VIỆC TAY SAU KHI DEPLOY ────────────────────────────────────────────────
-- update public.tool_pricing set enabled = true, updated_at = now()
--  where tool_id = 'duyen-no-tien-kiep';
