-- ============================================================================
-- U4 — SỔ LÁ SỐ theo TÀI KHOẢN
-- ----------------------------------------------------------------------------
-- 🔴 Đây là vá LỖI, không phải thêm tính năng.
--
-- `Shell.getRememberedBirth()` đọc `localStorage['app_birth']` ⇒ lá số nhớ theo
-- MÁY chứ không theo TÀI KHOẢN. Đổi máy / mở ẩn danh / xoá cache là mất sạch,
-- KỂ CẢ người đã đăng nhập và đã trả tiền. Và nó chỉ giữ được MỘT lá số: ai vừa
-- xem cho mình vừa xem cho vợ thì hai lá số ghi đè lẫn nhau.
--
-- 🔑 QUAN HỆ VỚI localStorage — đọc kỹ trước khi sửa:
-- localStorage KHÔNG bị bỏ. Nó vẫn là tầng đọc ĐỒNG BỘ mà `prefillForm()` dùng
-- lúc trang vừa mở (mọi tool gọi nó ở init). Bảng này là tầng BỀN nằm trên:
-- ghi thì ghi cả hai, đọc thì localStorage trước rồi mới đồng bộ từ server.
-- Đảo thứ tự đó là biến một hàm đồng bộ thành bất đồng bộ, và mọi trang tool
-- sẽ chớp một form trống trước khi điền — hỏng đúng chỗ người dùng nhìn đầu tiên.
--
-- `chart_key` gồm CẢ NHÃN chứ không chỉ ngày sinh: hai người sinh cùng ngày
-- cùng giờ cùng giới là chuyện có thật (sinh đôi, hoặc hai người quen). Khoá
-- chỉ theo ngày sinh thì lưu người thứ hai sẽ ĐÈ mất người thứ nhất.
-- ============================================================================

create table if not exists public.user_charts (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null references auth.users(id) on delete cascade,
  -- Nhãn người dùng tự đặt: "Tôi", "Vợ", "Sếp"… Rỗng = lá số đang dùng gần nhất
  -- (do tool tự lưu khi chạy), không phải mục người dùng cố ý đặt tên.
  label       text not null default '',
  -- Toàn bộ shape birth của TuviForm (hoten/ngay/thang/nam/gioHour/gioPhut/
  -- gioitinh/namxem). Lưu nguyên khối thay vì tách cột: shape này do client
  -- quyết định và đã đổi vài lần; tách cột là mỗi lần đổi một migration.
  birth       jsonb not null,
  chart_key   text not null,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  last_used_at timestamptz not null default now(),
  unique (user_id, chart_key)
);

create index if not exists user_charts_user_idx
  on public.user_charts (user_id, last_used_at desc);

alter table public.user_charts enable row level security;

-- ⚠️ Bảng này chứa NGÀY SINH CỦA NGƯỜI KHÁC (vợ, con, sếp) — dữ liệu cá nhân
-- của bên thứ ba mà người dùng nhập hộ. Chỉ chủ sổ được đọc; ghi/xoá đi qua
-- route server bằng service key, không mở cho anon.
drop policy if exists user_charts_owner_read on public.user_charts;
create policy user_charts_owner_read on public.user_charts
  for select using (auth.uid() = user_id);

-- CỐ Ý KHÔNG có policy cho admin: sổ lá số không phải dữ liệu vận hành, không
-- có lý do nghiệp vụ nào để admin đọc ngày sinh gia đình người dùng.

comment on table public.user_charts is
  'So la so theo tai khoan (U4). Chua ngay sinh cua nguoi khac -> chi chu so duoc doc.';
