-- _patches/migration-momo-settle.sql
-- ============================================================
-- Bảng đơn + cửa chốt NGUYÊN TỬ cho MoMo — CÙNG một khuôn với
-- `bank_orders`/`bank_settle_topup` (migration-bank-settle.sql): IPN có thể
-- gửi lại, hai lượt chốt song song cho cùng một đơn phải chỉ cộng Lượng MỘT
-- lần. Dùng một BẢNG (như bank), không dùng cột UNIQUE trên
-- `credit_transactions` (như paypal): route tạo đơn cần một chỗ để LƯU
-- `user_id`/`credits`/`label` trước khi khách rời trang sang MoMo — không có
-- API "đọc lại đơn theo id" nào của MoMo được gọi ở đây để tự suy lại ba thứ
-- đó, khác PayPal (route capture đọc lại đơn qua API PayPal).
--
-- ⚠️ Chưa dùng tới — bảng/hàm này chỉ được CHẠM khi `MOMO_PARTNER_CODE` +
-- `MOMO_ACCESS_KEY` + `MOMO_SECRET_KEY` có trên Vercel (xem
-- `lib/billing/momo.ts`). Áp migration này TRƯỚC khi set ba biến đó là an
-- toàn — không có dòng nào đọc/ghi bảng `momo_orders` cho tới lúc đó.
-- ============================================================

create table if not exists public.momo_orders (
  id          bigint generated by default as identity primary key,
  order_id    text not null unique,
  user_id     uuid not null,
  package_id  text not null,
  amount_vnd  integer not null,
  credits     integer not null,
  label       text,
  status      text default 'pending',
  paid_at     timestamptz,
  created_at  timestamptz default now()
);

create index if not exists idx_momo_orders_order_id on public.momo_orders (order_id);

-- RLS bật, KHÔNG policy nào — chỉ service key (bypass RLS) đọc/ghi được,
-- giống hệt `bank_orders`. Client không bao giờ chạm bảng này trực tiếp.
alter table public.momo_orders enable row level security;

-- ── Cửa DUY NHẤT để chốt một đơn topup MoMo ─────────────────────────────
-- `credited=false` KHÔNG phải lỗi — nghĩa là đơn đã có người chốt trước (IPN
-- gửi lại), hoặc không đủ điều kiện chốt. `reason` chỉ để bên gọi ghi log.
create or replace function public.momo_settle_topup(
  p_order_id   text,
  p_amount_vnd integer
)
returns table (credited boolean, reason text, balance integer, credits integer)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_user_id uuid;
  v_credits integer;
  v_label   text;
  v_balance integer;
  v_status  text;
begin
  -- MUTEX: chính dòng `momo_orders` là chỗ giành quyền, y hệt `bank_settle_topup`.
  -- ⚠️ Mọi cột trong thân RETURNS TABLE phải ghi kèm tên bảng — trùng tên OUT
  -- param (`credits`/`balance`) để trần là 42702, hàm chết hoàn toàn.
  update momo_orders mo
     set status  = 'paid',
         paid_at = now()
   where mo.order_id    = p_order_id
     and mo.status      = 'pending'
     and p_amount_vnd  >= mo.amount_vnd
  returning mo.user_id, mo.credits, mo.label
       into v_user_id, v_credits, v_label;

  if not found then
    select mo.status into v_status
      from momo_orders mo
     where mo.order_id = p_order_id;

    if v_status is null then
      return query select false, 'not_found'::text, 0, 0;
    elsif v_status <> 'pending' then
      return query select false, ('already_' || v_status)::text, 0, 0;
    else
      return query select false, 'amount_mismatch'::text, 0, 0;
    end if;
    return;
  end if;

  -- Dòng SỔ đi TRƯỚC, cùng transaction với UPDATE ở trên.
  insert into credit_transactions
    (user_id, amount, type, description, amount_vnd, gateway)
  values
    (v_user_id, v_credits, 'topup', coalesce(v_label, 'Nap credits MoMo'), p_amount_vnd, 'momo');

  -- Qua `add_credits` — UPSERT, sổ giao dịch phải giải thích được số dư.
  v_balance := add_credits(v_user_id, v_credits);
  return query select true, 'ok'::text, v_balance, v_credits;
end;
$$;

-- SECURITY DEFINER mới LUÔN sinh ra hở: EXECUTE cho PUBLIC là dựng sẵn của
-- Postgres. Hàm này cộng Lượng — chỉ service key được gọi.
revoke all on function public.momo_settle_topup(text, integer)
  from public, anon, authenticated;
grant execute on function public.momo_settle_topup(text, integer)
  to service_role;
