/** @type {import('next').NextConfig} */
const nextConfig = {
  trailingSlash: false,
  async rewrites() {
    return [
      { source: '/',                    destination: '/index.html'           },
      { source: '/app',                 destination: '/app-home.html'        },
      { source: '/app/la-so',           destination: '/app.html'             },
      { source: '/app/luan-giai',       destination: '/app-luan-giai.html'   },
      { source: '/app/bat-tu',          destination: '/app-bat-tu.html'      },
      { source: '/app/xem-tuoi',        destination: '/app-xem-tuoi.html'    },
      { source: '/app/xem-lam-an',      destination: '/app-xem-tuoi.html'    },
      { source: '/app/tuong-hop',       destination: '/app-xem-tuoi.html'    },
      { source: '/app/sinh-con',        destination: '/app-sinh-con.html'    },
      { source: '/app/dat-ten',         destination: '/app-dat-ten.html'     },
      { source: '/app/dat-ten-dn',      destination: '/app-dat-ten-dn.html'  },
      { source: '/app/ngu-hanh-ten',    destination: '/app-ngu-hanh-ten.html'},
      { source: '/app/chon-ngay',       destination: '/app-chon-ngay.html'   },
      { source: '/app/kim-lau',         destination: '/app-kim-lau.html'     },
      { source: '/app/xem-tuong',       destination: '/app-xem-tuong.html'   },
      { source: '/app/phong-thuy',      destination: '/app-phong-thuy.html'  },
      { source: '/app/bat-trach',       destination: '/app-bat-trach.html'   },
      { source: '/app/nap-am',          destination: '/app-nap-am.html'      },
      { source: '/app/than-so-hoc',     destination: '/app-than-so-hoc.html' },
      { source: '/app/kinh-dich',       destination: '/app-kinh-dich.html'   },
      { source: '/app/tai-khoan',       destination: '/app-tai-khoan.html'   },
      { source: '/xem-tuoi',            destination: '/xem-tuoi.html'        },
      { source: '/xem-lam-an',          destination: '/xem-lam-an.html'      },
      { source: '/la-so',               destination: '/la-so.html'           },
      { source: '/la-so-v2',            destination: '/la-so-v2.html'        },
      { source: '/menh-kho',            destination: '/menh-kho.html'        },
      { source: '/cong-cu',             destination: '/cong-cu.html'         },
      { source: '/profile',             destination: '/profile.html'         },
      { source: '/about',               destination: '/about.html'           },
      { source: '/contact',             destination: '/contact.html'         },
      { source: '/resources',           destination: '/resources.html'       },
      { source: '/blog',                destination: '/blog.html'            },
      { source: '/payment-success',     destination: '/payment-success.html' },
      { source: '/auth-callback',       destination: '/auth-callback.html'   },
      { source: '/tai-lieu/:slug',      destination: '/tai-lieu.html'        },
      { source: '/tai-lieu/sach/:slug', destination: '/sach-detail.html'     },
      { source: '/sitemap.xml',         destination: '/api/sitemap'          },
      { source: '/sitemap-ngay-tot.xml', destination: '/sitemap-ngay-tot'    },
      { source: '/sitemap-hubs.xml',    destination: '/sitemap-hubs'         },
      { source: '/sitemap-pregen.xml',  destination: '/sitemap-pregen'       },
      { source: '/khao-luan/:slug',     destination: '/api/khao-luan?slug=:slug' },
      { source: '/tu-vi/:slug',         destination: '/api/tu-vi?slug=:slug'     },
      { source: '/phong-thuy',          destination: '/api/tu-vi-hub?cat=phong-thuy'   },
      { source: '/xem-tuong',           destination: '/api/tu-vi-hub?cat=xem-tuong'    },
      { source: '/chon-ngay',           destination: '/api/tu-vi-hub?cat=chon-ngay'    },
      { source: '/lam-dep',             destination: '/api/tu-vi-hub?cat=lam-dep'      },
      { source: '/dat-ten',             destination: '/api/tu-vi-hub?cat=dat-ten'      },
      { source: '/kien-thuc-tuvi',      destination: '/api/tu-vi-hub?cat=kien-thuc-tuvi' },
    ];
  },
};

export default nextConfig;
